[build]
  publish = "dist"
  command = "npm ci --include=dev && npm run build"

[context.production]
  environment = { NODE_ENV = "production", NPM_FLAGS = "--include=dev", NODE_VERSION = "18" }

[functions]
  directory = "netlify/functions"
